parameters:
  extension: false

jobs:
- job: RetainRun
  pool:
    name: default
  workspace:
    clean: all
  variables:
  - template: variables.yml
  steps:
  - checkout: RetainRun
  - template: steps/build.yml
    parameters:
      path: ${{ variables.taskPath }}
      restore: true
      lint: true
      build: true
      test: true
      clean: true
      publish: true

- ${{ if eq(parameters.extension, true) }}:
  - job: Extension
    pool:
      name: default
    workspace:
      clean: all
    variables:
    - template: variables.yml
    dependsOn:
    - RetainRun
    steps:
    - checkout: RetainRun
    - template: steps/package.yml
      parameters:
        path: ${{ variables.artifactsPath }}
        endpointName: ${{ variables.marketplaceEndpoint }}
        publisherId: ${{ variables.publisherId }}
        extensionId: ${{ variables.extensionId }}
        extensionName: ${{ variables.extensionName }}
        contents: |
          Docs/**
          Images/**
          *.md
          *.json
        publish: true
