parameters:
  path: ""
  contents: ""
  publish: false

steps:
- task: TfxInstaller@3
  displayName: Install Node CLI

- task: CopyFiles@2
  displayName: Copy extension
  inputs:
    contents: ${{ parameters.contents }}
    targetFolder: ${{ parameters.path }}

- task: DownloadPipelineArtifact@2
  displayName: Copy tasks
  inputs:
    source: current
    path: ${{ parameters.path }}/Tasks

- task: PackageAzureDevOpsExtension@3
  displayName: Package extension
  inputs:
    rootFolder: ${{ parameters.path }}
    outputVariable: extensionPath

- ${{ if eq(parameters.publish, true) }}:
  - publish: $(extensionPath)
    displayName: Publish artifact
    artifact: Extension
