trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - ci/*
    - task/*
  autoCancel: true

resources:
  repositories:
  - repository: RetainRun
    type: github
    name: alexalnaib/RetainRun
    ref: refs/heads/master
    endpoint: alexalnaib

jobs:
- checkout: RetainRun
- template: templates/build.yml
  parameters:
    extension: true
