trigger:
  branches:
    include:
    - master
  paths:
    include:
    - task/*

resources:
  repositories:
  - repository: RetainRun
    type: github
    name: alexalnaib/RetainRun
    ref: refs/heads/master
    endpoint: alexalnaib

stages:
- stage: Build
  jobs:
  - template: templates/build.yml
    parameters:
      extension: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - template: templates/preview.yml
    parameters:
      environmentName: Marketplace

- stage: Release
  dependsOn:
  - Build
  - Preview
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: templates/release.yml
    parameter:
      environmentName: Marketplace
