trigger: none

resources:
  repositories:
  - repository: RetainRun
    type: github
    name: alexalnaib/RetainRun
    ref: refs/heads/master
    endpoint: alexalnaib

stages:
- stage: RetainRun
  dependsOn: []
  jobs:
  - template: templates/test.yml

- stage: nothing
  dependsOn:: RetainRun
  jobs:
    - job: nothing
      steps:
      - script: echo "Hello World"
